//! Bitwarden refs file write / merge (setup + refresh).

use std::fs;
use std::path::Path;

use crate::error::{Error, Result};
use crate::validate::is_uuid;

pub fn key_to_var(key: &str) -> String {
    let mut s: String = key
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    if s.is_empty() || !s.chars().next().unwrap().is_ascii_alphabetic() && s.chars().next() != Some('_')
    {
        s = format!("SECRET_{s}");
    }
    if !s.starts_with(|c: char| c.is_ascii_alphabetic() || c == '_') {
        s = format!("SECRET_{s}");
    }
    s
}

pub fn line_for_secret(id: &str, key: &str) -> String {
    if !key.is_empty()
        && key
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.' || c == '/' || c == '-')
    {
        format!("{}=name:{key}\n", key_to_var(key))
    } else {
        format!("SECRET={id}\n")
    }
}

/// True if the refs file already maps this secret (id or name:KEY on a VAR= line).
fn text_has_secret(text: &str, id: &str, key: &str) -> bool {
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') || !line.contains('=') {
            continue;
        }
        let Some((_, v)) = line.split_once('=') else {
            continue;
        };
        let r = v.trim();
        if !id.is_empty() {
            if r == id || r == format!("uuid:{id}") {
                return true;
            }
        }
        if !key.is_empty() {
            if r == format!("name:{key}") {
                return true;
            }
            // project:PROJECT/KEY also counts as mapped for this key
            if let Some(rest) = r.strip_prefix("project:") {
                if rest.rsplit_once('/').map(|(_, s)| s) == Some(key) {
                    return true;
                }
            }
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn substring_uuid_in_comment_is_not_a_hit() {
        let text = "# note about 00000000-0000-0000-0000-000000000001\nOPENAI=name:other\n";
        assert!(!text_has_secret(
            text,
            "00000000-0000-0000-0000-000000000001",
            "openai-api-key"
        ));
    }

    #[test]
    fn name_ref_line_is_a_hit() {
        let text = "OPENAI_API_KEY=name:openai-api-key\n";
        assert!(text_has_secret(text, "id-x", "openai-api-key"));
    }

    #[test]
    fn bare_uuid_value_is_a_hit() {
        let text = "X=00000000-0000-0000-0000-000000000099\n";
        assert!(text_has_secret(
            text,
            "00000000-0000-0000-0000-000000000099",
            "anything"
        ));
    }
}

pub fn write_refs_replace(
    path: &Path,
    secrets: &[(String, String, String)],
    indices: Option<&[usize]>,
    source: &str,
) -> Result<()> {
    let mut body = format!(
        "# Bitwarden Secrets Manager refs (no secret values). Generated by {source}.\n\
         # Forms: UUID | uuid:UUID | name:KEY | project:PROJECT/KEY\n\
         # Update: vaulted-agent refresh\n\
         # Values fetched live at launch.\n\n"
    );
    for (i, (id, key, _)) in secrets.iter().enumerate() {
        if let Some(sel) = indices {
            if !sel.contains(&i) {
                continue;
            }
        }
        body.push_str(&line_for_secret(id, key));
    }
    fs::write(path, body).map_err(|e| Error::Io {
        path: path.to_path_buf(),
        source: e,
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut p = fs::metadata(path)
            .map_err(|e| Error::Io {
                path: path.to_path_buf(),
                source: e,
            })?
            .permissions();
        p.set_mode(0o644);
        let _ = fs::set_permissions(path, p);
    }
    Ok(())
}

pub fn write_refs_merge(
    path: &Path,
    secrets: &[(String, String, String)],
    indices: Option<&[usize]>,
    source: &str,
) -> Result<usize> {
    let existing = if path.is_file() {
        fs::read_to_string(path).map_err(|e| Error::Io {
            path: path.to_path_buf(),
            source: e,
        })?
    } else {
        String::new()
    };
    let mut new_lines = String::new();
    let mut added = 0usize;
    for (i, (id, key, _)) in secrets.iter().enumerate() {
        if let Some(sel) = indices {
            if !sel.contains(&i) {
                continue;
            }
        }
        if text_has_secret(&existing, id, key) {
            continue;
        }
        new_lines.push_str(&line_for_secret(id, key));
        added += 1;
    }
    if added == 0 {
        return Ok(0);
    }
    let body = if existing.is_empty() {
        format!(
            "# Bitwarden Secrets Manager refs (no secret values). Generated by {source}.\n\n{new_lines}"
        )
    } else {
        format!("{existing}\n\n# --- appended by {source} ---\n{new_lines}")
    };
    fs::write(path, body).map_err(|e| Error::Io {
        path: path.to_path_buf(),
        source: e,
    })?;
    Ok(added)
}

pub fn parse_index_list(s: &str, n: usize) -> Result<Vec<usize>> {
    if s == "all" {
        return Ok((0..n).collect());
    }
    let mut out = Vec::new();
    for part in s.split(',') {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        let num: usize = part
            .parse()
            .map_err(|_| Error::Message(format!("bad index {part}")))?;
        if num == 0 || num > n {
            return Err(Error::Message(format!("index out of range: {num}")));
        }
        out.push(num - 1);
    }
    Ok(out)
}

#[allow(dead_code)]
pub fn is_uuid_pub(s: &str) -> bool {
    is_uuid(s)
}
