//! Bitwarden refs file write / merge (setup + refresh).

use std::fs;
use std::path::Path;

use crate::error::{Error, Result};

pub fn key_to_var(key: &str) -> String {
    let mut s: String = key
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    let needs_prefix = !matches!(s.chars().next(), Some(c) if c.is_ascii_alphabetic() || c == '_');
    if needs_prefix {
        s = format!("SECRET_{s}");
    }
    s
}

pub fn line_for_secret(id: &str, key: &str) -> String {
    if !key.is_empty()
        && key
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.' || c == '/' || c == '-')
    {
        format!("{}=name:{key}\n", key_to_var(key))
    } else {
        format!("SECRET={id}\n")
    }
}

fn var_from_line(line: &str) -> Option<&str> {
    line.split_once('=').map(|(k, _)| k.trim())
}

/// True if the refs file already maps this secret by reference (id / name:KEY / project:…/KEY).
fn text_has_secret(text: &str, id: &str, key: &str) -> bool {
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') || !line.contains('=') {
            continue;
        }
        let Some((_, v)) = line.split_once('=') else {
            continue;
        };
        let r = v.trim();
        if !id.is_empty() && (r == id || r == format!("uuid:{id}")) {
            return true;
        }
        if !key.is_empty() {
            if r == format!("name:{key}") {
                return true;
            }
            // project:PROJECT/KEY also counts as mapped for this key
            if let Some(rest) = r.strip_prefix("project:") {
                if rest.rsplit_once('/').map(|(_, s)| s) == Some(key) {
                    return true;
                }
            }
        }
    }
    false
}

/// True if a VAR= line already exists (protects hand-edited custom mappings; story #14).
fn text_has_var(text: &str, var: &str) -> bool {
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') || !line.contains('=') {
            continue;
        }
        if var_from_line(line) == Some(var) {
            return true;
        }
    }
    false
}

pub fn write_refs_replace(
    path: &Path,
    secrets: &[(String, String, String)],
    indices: Option<&[usize]>,
    source: &str,
) -> Result<()> {
    let mut body = format!(
        "# Bitwarden Secrets Manager refs (no secret values). Generated by {source}.\n\
         # Forms: UUID | uuid:UUID | name:KEY | project:PROJECT/KEY\n\
         # Update: vaulted-agent refresh\n\
         # Values fetched live at launch.\n\n"
    );
    let mut seen_vars = std::collections::HashSet::new();
    for (i, (id, key, _)) in secrets.iter().enumerate() {
        if let Some(sel) = indices {
            if !sel.contains(&i) {
                continue;
            }
        }
        let line = line_for_secret(id, key);
        let var = var_from_line(line.trim()).unwrap_or("SECRET");
        if !seen_vars.insert(var.to_string()) {
            continue;
        }
        body.push_str(&line);
    }
    fs::write(path, body).map_err(|e| Error::Io {
        path: path.to_path_buf(),
        source: e,
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut p = fs::metadata(path)
            .map_err(|e| Error::Io {
                path: path.to_path_buf(),
                source: e,
            })?
            .permissions();
        p.set_mode(0o644);
        let _ = fs::set_permissions(path, p);
    }
    Ok(())
}

pub fn write_refs_merge(
    path: &Path,
    secrets: &[(String, String, String)],
    indices: Option<&[usize]>,
    source: &str,
) -> Result<usize> {
    let existing = if path.is_file() {
        fs::read_to_string(path).map_err(|e| Error::Io {
            path: path.to_path_buf(),
            source: e,
        })?
    } else {
        String::new()
    };
    let mut new_lines = String::new();
    let mut added = 0usize;
    // Track VARs newly claimed this pass (existing checked via text_has_var).
    let mut claimed = std::collections::HashSet::new();

    for (i, (id, key, _)) in secrets.iter().enumerate() {
        if let Some(sel) = indices {
            if !sel.contains(&i) {
                continue;
            }
        }
        if text_has_secret(&existing, id, key) {
            continue;
        }
        let line = line_for_secret(id, key);
        let var = var_from_line(line.trim()).unwrap_or("SECRET").to_string();
        // Story #14: never append a second mapping under a VAR the operator already pinned.
        if text_has_var(&existing, &var) || !claimed.insert(var) {
            continue;
        }
        new_lines.push_str(&line);
        added += 1;
    }
    if added == 0 {
        return Ok(0);
    }
    let body = if existing.is_empty() {
        format!(
            "# Bitwarden Secrets Manager refs (no secret values). Generated by {source}.\n\n{new_lines}"
        )
    } else {
        format!("{existing}\n\n# --- appended by {source} ---\n{new_lines}")
    };
    fs::write(path, body).map_err(|e| Error::Io {
        path: path.to_path_buf(),
        source: e,
    })?;
    Ok(added)
}

/// VAR name for a 1Password field: "anthropic" + "conductor-api-key" becomes
/// ANTHROPIC_CONDUCTOR_API_KEY. The section is included when the field is in
/// one, because label alone is not unique within an item.
pub fn op_ref_var(item: &str, section: Option<&str>, field: &str) -> String {
    let joined = match section {
        Some(s) if !s.is_empty() => format!("{item}_{s}_{field}"),
        _ => format!("{item}_{field}"),
    };
    let mut s: String = joined
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    while s.contains("__") {
        s = s.replace("__", "_");
    }
    let s = s.trim_matches('_').to_string();
    let needs_prefix = !matches!(s.chars().next(), Some(c) if c.is_ascii_alphabetic());
    if needs_prefix {
        format!("SECRET_{s}")
    } else {
        s
    }
}

/// `op://VAULT/ITEM/FIELD`, or `op://VAULT/ITEM/SECTION/FIELD` for a field in a
/// section.
///
/// The section is not decoration. An item can carry several fields with the same
/// label in different sections, holding different secrets; the unqualified form
/// then resolves to whichever one `op` picks. Both forms were checked against a
/// real vault, including that two section-qualified references return different
/// values.
///
/// Spaces are fine: `op inject` reads a dotenv value to end of line.
pub fn op_reference(vault: &str, item: &str, section: Option<&str>, field: &str) -> String {
    match section {
        Some(s) if !s.is_empty() => format!("op://{vault}/{item}/{s}/{field}"),
        _ => format!("op://{vault}/{item}/{field}"),
    }
}

/// True when a reference component survives `op inject`'s reference scanner.
///
/// The scanner ends a reference at a character it does not accept, so an item
/// titled `db-admin jstephens MySQL (read-write)` is read as the truncated
/// `op://Orchestrator/db-admin jstephens MySQL` and rejected with "too few
/// '/'": one such item aborts the injection of the entire manifest. Spaces are
/// accepted; parentheses and non-ASCII characters (an em dash in a title, say)
/// are not. Quoting the value is not a workaround, because the scanner runs
/// over the reference text itself rather than the shell-quoted line.
pub fn op_component_is_safe(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | ' '))
}

/// True when `op` can read a whole reference: the scheme, then at least a
/// vault, an item and a field, each built only from characters its scanner
/// accepts. One reference that fails this aborts the injection of the entire
/// manifest, so it is worth checking before a launch rather than during one.
pub fn op_reference_is_parseable(reference: &str) -> bool {
    let Some(rest) = reference.strip_prefix("op://") else {
        return false;
    };
    let parts: Vec<&str> = rest.split('/').collect();
    parts.len() >= 3 && parts.iter().all(|p| op_component_is_safe(p))
}

/// The item component of a reference: the readable title when `op` can parse
/// it, otherwise the item's opaque ID, which always parses. Variable names are
/// still derived from the title, so a fallback here costs readability only in
/// the reference itself.
pub fn op_item_component<'a>(title: &'a str, id: &'a str) -> &'a str {
    if op_component_is_safe(title) {
        title
    } else {
        id
    }
}

/// True if the refs file already points at this exact reference.
fn text_has_reference(text: &str, reference: &str) -> bool {
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((_, v)) = line.split_once('=') {
            if v.trim() == reference {
                return true;
            }
        }
    }
    false
}

const OP_REFS_HEADER: &str = "1Password refs (no secret values). Generated by";

/// Write a 1Password refs manifest from (var, reference) pairs, replacing any
/// existing content.
pub fn write_op_refs_replace(
    path: &Path,
    entries: &[(String, String)],
    source: &str,
) -> Result<()> {
    // The form line deliberately does not spell out a literal reference.
    // `op inject` substitutes every reference it finds in the file, comments
    // included, so an illustrative op://VAULT/ITEM/FIELD in this header is read
    // as a real reference and the whole injection dies on "VAULT isn't a vault
    // in this account" - taking every genuine entry below it down too.
    let mut body = format!(
        "# {OP_REFS_HEADER} {source}.\n\
         # Form: VAR= a secret reference (vault, item and field, slash separated).\n\
         # Update: vaulted-agent refresh\n\
         # Values fetched live at launch.\n\n"
    );
    let mut seen = std::collections::HashSet::new();
    for (var, reference) in entries {
        if !seen.insert(var.clone()) {
            continue;
        }
        body.push_str(&format!("{var}={reference}\n"));
    }
    fs::write(path, body).map_err(|e| Error::Io {
        path: path.to_path_buf(),
        source: e,
    })?;
    set_refs_mode(path);
    Ok(())
}

/// Append only the (var, reference) pairs not already mapped. Returns how many
/// were added.
pub fn write_op_refs_merge(
    path: &Path,
    entries: &[(String, String)],
    source: &str,
) -> Result<usize> {
    let existing = if path.is_file() {
        fs::read_to_string(path).map_err(|e| Error::Io {
            path: path.to_path_buf(),
            source: e,
        })?
    } else {
        String::new()
    };
    let mut new_lines = String::new();
    let mut added = 0usize;
    let mut claimed = std::collections::HashSet::new();

    for (var, reference) in entries {
        if text_has_reference(&existing, reference) {
            continue;
        }
        // Never append a second mapping under a VAR the operator already pinned.
        if text_has_var(&existing, var) || !claimed.insert(var.clone()) {
            continue;
        }
        new_lines.push_str(&format!("{var}={reference}\n"));
        added += 1;
    }
    if added == 0 {
        return Ok(0);
    }
    let body = if existing.is_empty() {
        format!("# {OP_REFS_HEADER} {source}.\n\n{new_lines}")
    } else {
        format!("{existing}\n\n# --- appended by {source} ---\n{new_lines}")
    };
    fs::write(path, body).map_err(|e| Error::Io {
        path: path.to_path_buf(),
        source: e,
    })?;
    set_refs_mode(path);
    Ok(added)
}

fn set_refs_mode(path: &Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(md) = fs::metadata(path) {
            let mut p = md.permissions();
            p.set_mode(0o644);
            let _ = fs::set_permissions(path, p);
        }
    }
    #[cfg(not(unix))]
    let _ = path;
}

pub fn parse_index_list(s: &str, n: usize) -> Result<Vec<usize>> {
    if s == "all" {
        return Ok((0..n).collect());
    }
    let mut out = Vec::new();
    for part in s.split(',') {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        let num: usize = part
            .parse()
            .map_err(|_| Error::Message(format!("bad index {part}")))?;
        if num == 0 || num > n {
            return Err(Error::Message(format!("index out of range: {num}")));
        }
        out.push(num - 1);
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn substring_uuid_in_comment_is_not_a_hit() {
        let text = "# note about 00000000-0000-0000-0000-000000000001\nOPENAI=name:other\n";
        assert!(!text_has_secret(
            text,
            "00000000-0000-0000-0000-000000000001",
            "openai-api-key"
        ));
    }

    #[test]
    fn name_ref_line_is_a_hit() {
        let text = "OPENAI_API_KEY=name:openai-api-key\n";
        assert!(text_has_secret(text, "id-x", "openai-api-key"));
    }

    #[test]
    fn bare_uuid_value_is_a_hit() {
        let text = "X=00000000-0000-0000-0000-000000000099\n";
        assert!(text_has_secret(
            text,
            "00000000-0000-0000-0000-000000000099",
            "anything"
        ));
    }

    #[test]
    fn op_var_uppercases_and_collapses_separators() {
        assert_eq!(
            op_ref_var("anthropic", None, "conductor-api-key"),
            "ANTHROPIC_CONDUCTOR_API_KEY"
        );
        assert_eq!(
            op_ref_var("github token", None, "fine-grained-token"),
            "GITHUB_TOKEN_FINE_GRAINED_TOKEN"
        );
        // Leading/trailing junk must not produce __ or a trailing _.
        assert_eq!(op_ref_var("  spaced  ", None, "-field-"), "SPACED_FIELD");
    }

    #[test]
    fn op_var_prefixes_when_it_would_not_start_with_a_letter() {
        // A bare digit start is not a valid shell identifier.
        assert_eq!(op_ref_var("3cx", None, "api-key"), "SECRET_3CX_API_KEY");
    }

    #[test]
    fn section_distinguishes_same_label_fields() {
        // Without the section these collapse to one VAR and one ambiguous
        // reference, silently dropping real secrets.
        let a = op_ref_var("mysql8.etadventures.com", Some("mysql"), "password");
        let b = op_ref_var("mysql8.etadventures.com", None, "password");
        assert_eq!(a, "MYSQL8_ETADVENTURES_COM_MYSQL_PASSWORD");
        assert_eq!(b, "MYSQL8_ETADVENTURES_COM_PASSWORD");
        assert_ne!(a, b);

        assert_eq!(
            op_reference("V", "host", Some("mysql"), "password"),
            "op://V/host/mysql/password"
        );
        assert_eq!(
            op_reference("V", "host", None, "password"),
            "op://V/host/password"
        );
        // An empty section must not produce a double slash.
        assert_eq!(
            op_reference("V", "host", Some(""), "password"),
            "op://V/host/password"
        );
    }

    #[test]
    fn op_component_safety_matches_what_op_can_parse() {
        // Spaces are accepted by op's reference scanner.
        assert!(op_component_is_safe("db-admin jstephens MySQL"));
        assert!(op_component_is_safe("mysql8.etadventures.com"));
        assert!(op_component_is_safe("add more"));
        // These end the reference early, so op reports "too few '/'".
        assert!(!op_component_is_safe(
            "db-admin jstephens MySQL (read-write)"
        ));
        assert!(!op_component_is_safe("Grafana — grafana.etadventures.com"));
        assert!(!op_component_is_safe(""));
    }

    #[test]
    fn unparseable_item_title_falls_back_to_the_id() {
        let id = "7vjm6j5srnx2krtk5nvduzjjoe";
        assert_eq!(op_item_component("plain-title", id), "plain-title");
        assert_eq!(op_item_component("db-admin (read-write)", id), id);
        // The variable name still comes from the title, so the fallback costs
        // readability only inside the reference.
        assert_eq!(
            op_ref_var("db-admin (read-write)", None, "username"),
            "DB_ADMIN_READ_WRITE_USERNAME"
        );
        assert_eq!(
            op_reference(
                "V",
                op_item_component("db-admin (read-write)", id),
                None,
                "username"
            ),
            format!("op://V/{id}/username")
        );
    }

    #[test]
    fn reference_parseability_matches_op() {
        assert!(op_reference_is_parseable("op://V/item/field"));
        assert!(op_reference_is_parseable("op://V/item/add more/field"));
        assert!(op_reference_is_parseable(
            "op://V/db-admin jstephens/username"
        ));
        // Truncated by op's scanner, so op reports "too few '/'".
        assert!(!op_reference_is_parseable(
            "op://V/db-admin (read-write)/username"
        ));
        assert!(!op_reference_is_parseable("op://V/Grafana — host/username"));
        // Genuinely too few components, before any character question.
        assert!(!op_reference_is_parseable("op://V/item"));
        // Not a 1Password reference at all.
        assert!(!op_reference_is_parseable("name:some-secret"));
    }

    #[test]
    fn generated_header_carries_no_resolvable_reference() {
        // `op inject` resolves every reference in the file, comments included.
        // An illustrative op://VAULT/ITEM/FIELD in the header is therefore a
        // real lookup that fails, and one failed lookup aborts the injection of
        // the entire manifest. Only lines written by refresh may contain a
        // reference, and every one of those is a genuine entry.
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("op.refs");
        let entries = vec![(
            "A_KEY".to_string(),
            "op://V/anthropic/conductor-api-key".to_string(),
        )];
        write_op_refs_replace(&p, &entries, "test").unwrap();

        for line in fs::read_to_string(&p).unwrap().lines() {
            if line.trim_start().starts_with('#') {
                assert!(
                    !line.contains("op://"),
                    "header comment carries a reference op inject would try to resolve: {line}"
                );
            }
        }
    }

    #[test]
    fn op_merge_skips_references_and_vars_already_present() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("op.refs");

        let entries = vec![
            (
                "A_KEY".to_string(),
                "op://V/anthropic/conductor-api-key".to_string(),
            ),
            ("B_KEY".to_string(), "op://V/github token/tok".to_string()),
        ];
        write_op_refs_replace(&p, &entries, "test").unwrap();
        let first = fs::read_to_string(&p).unwrap();
        assert!(first.contains("A_KEY=op://V/anthropic/conductor-api-key"));

        // Same entries again: nothing new.
        assert_eq!(write_op_refs_merge(&p, &entries, "test").unwrap(), 0);
        assert_eq!(fs::read_to_string(&p).unwrap(), first);

        // A new reference under a VAR the operator already pinned is skipped
        // rather than appended as a second mapping.
        let clash = vec![("A_KEY".to_string(), "op://V/other/field".to_string())];
        assert_eq!(write_op_refs_merge(&p, &clash, "test").unwrap(), 0);

        // A genuinely new one is appended.
        let fresh = vec![("C_KEY".to_string(), "op://V/third/field".to_string())];
        assert_eq!(write_op_refs_merge(&p, &fresh, "test").unwrap(), 1);
        assert!(fs::read_to_string(&p)
            .unwrap()
            .contains("C_KEY=op://V/third/field"));
    }

    #[test]
    fn merge_skips_when_var_already_mapped_to_different_ref() {
        let existing = "OPENAI_API_KEY=uuid:00000000-0000-0000-0000-000000000009\n";
        // Would produce OPENAI_API_KEY=name:openai.api.key — must not append.
        let line = line_for_secret("other-id", "openai.api.key");
        let var = var_from_line(line.trim()).unwrap();
        assert!(text_has_var(existing, var));
        assert!(!text_has_secret(existing, "other-id", "openai.api.key"));
    }
}
